services:
  api:
    image: asia-northeast3-docker.pkg.dev/cheorish/docker/api:0.0.1
    container_name: api
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - dairy_net

networks:
  dairy_net:
    external: True
