services:
  api:
    image: ${IMAGE_NAME}
    platform: linux/arm64
    container_name: api
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - dairy_net

networks:
  dairy_net:
    external: True
