services:
  api:
    image: ${IMAGE_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    ports:
      - "${PORT}:8000"
    networks:
      - dairy_net

networks:
  dairy_net:
    external: True