version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: project-app
    ports:
      - '8000:8000' # 필요한 포트 매핑
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis

  redis:
    image: redis:6.2
    container_name: project-redis
    ports:
      - '6379:6379'
