version: '3.8'

networks:
  mimd-network:
    external: true

services:
  app:
    image: cseeeee/fastapi-diary:latest
    container_name: project-app
    ports:
      - '8000:8000'
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
    networks:
      - mimd-network

  # redis:
  #   image: redis:6.2
  #   container_name: project-redis
  #   ports:
  #     - '6379:6379'
  # networks:
  #   - mimd-network
