services:
  airflow-webserver:
    image: ${IMAGE_NAME}
    platform: linux/arm64
    container_name: airflow-webserver

    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=${AIRFLOW__CORE__EXECUTOR}
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      - AIRFLOW__WEBSERVER__BASE_URL=${AIRFLOW__WEBSERVER__BASE_URL}
      - AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX=${AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX}
      - AIRFLOW__CORE__LOAD_EXAMPLES=${AIRFLOW__CORE__LOAD_EXAMPLES}
      - AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT=2000
    ports:
      - "${AIRFLOW_WEB_PORT}:8080"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    healthcheck:
      test: [ "CMD", "curl", "-f", "${URLS}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - dairy_net

networks:
  dairy_net:
    external: True