services:
  vector_stores:
    build: .
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - dairy_net

  set_password:
    image: redis/redis-stack:latest
    depends_on:
      - vector_stores
    command: redis-cli -h ${REDIS_HOST} -p ${REDIS_PORT} CONFIG SET requirepass ${REDIS_PASSWORD}
    networks:
      - dairy_net

networks:
  dairy_net:
    external: True