services:
  vector_stores:
    build: .
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - dairy_net

networks:
  dairy_net:
    external: True
