services:
  vector_stores:
    image: ${IMAGE_NAME}
    platform: linux/amd64
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "${REDIS_HOST}", "-p", "${REDIS_PORT}", "PING"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - dairy_net

networks:
  dairy_net:
    external: True